### ISSUE TITLE
Idea: Reloading Libraries

### ISSUE THREAD

**Issue by runxel** [tlorantfy/archicad-additional-json-commands#1]
Hi Tibor!
I have an idea what to implement next: **Reload libraries**.
This would be great for complementing the GDL VSCode addon (I'm the creator of the [original Sublime Text GDL-addon](https://github.com/runxel/GDL-sublime)).
This would smooth development a lot.

Have a great day!
Lucas

**Comment by tlorantfy** [comment]
See last commit:
https://github.com/tlorantfy/archicad-additional-json-commands/commit/277680285644f2f4382c035c887671bcaafc70ec
Thanks for the idea!
