### ISSUE TITLE
AC26 Build

### ISSUE THREAD

**Issue by scottjm-arch** [tlorantfy/archicad-additional-json-commands#2]
Would be great to get a compiled APX for AC26 for this.

Thanks,
Scott

**Comment by dushyant-basson** [comment]
I have built it for AC26. You can download it from the link below:
https://onizu.com/download/archicad-additional-json-commands-ac26.apx

**Comment by tlorantfy** [comment]
Thanks @dushyant-basson for solving the issue! I merged your pull request.
Sorry guys, since I left Graphisoft I don't have time for this project. But I hope I will come back and will keep it alive, update it with new features. Feel free to post your requests as issues here!

**Comment by joanaif** [comment]
Hi! Can you please help to build for AC26 Mac? thanks a lot
